### ISSUE TITLE
need to update command on how to run coverage and fix directory path  where riscof looks for elf

### ISSUE THREAD

**Issue by dansmathers** [riscv-software-src/riscv-config#135]
https://riscof.readthedocs.io/en/stable/coverage.html

The current directions say to run coverage: 
riscof --verbose debug coverage --suite /path/to/suite --env /path/to/suite

this will generate an error.    -c or --cgf_file is a required option.

However, even if -cgf_file is used, there is another error.  riscof looks for the elf file in the wrong directory:

FileNotFoundError: [Errno 2] No such file or directory: '<PATH>/riscof/riscof_work/rv32i_m/C/src/caddi-01.S/ref.elf'

but it looks like it should instead be looking in:
./rv32i_m/I/src/addi-01.S/ref/ref.elf

Thanks

**Comment by pawks** [comment]
I don't think the paths are wrong. Both would probably point to the same thing. All paths are resolved to be absolute paths before the actual execution of riscof starts. The former simply looks like the absolute path of the latter. I think the compilation was not successful. Can you share the entire log?

**Comment by neelgala** [comment]
@dansmathers its better to move/track this issue in the [riscof repo](https://github.com/riscv-software-src/riscof)  since it doesn't have anything to do with riscv-config.

**Comment by dansmathers** [comment]
moved to https://github.com/riscv-software-src/riscof/issues/94
closing here.
