### ISSUE TITLE
Linki points to itself

### ISSUE THREAD

**Issue by allenjbaum** [riscv-software-src/riscv-config#57]
On this page: https://github.com/riscv/riscv-config/blob/master/docs/source/overview.rst
Details of this input file can be found here : :ref:`isa_yaml_spec`.
The embedded link points back to this page.

**Comment by pawks** [comment]
The link is resolved when the doc is built using sphinx. The hyperlinks do not work when looking at the rst version of the docs. The hosted version of the docs can be found [here](https://riscv-config.readthedocs.io/en/latest/overview.html).

**Comment by Blacklion14** [comment]
Hello @pawks 
I saw along with the link @allenjbaum mentioned, these links also do not work in rst version but works after doc is built
  
- [rst version](https://github.com/riscv/riscv-config/blob/master/docs/source/new-extensions.rst#adding-support-for-new-extensions) ->For details on check_debug_specs() check here : :ref:`checker`.  
  and  works in [Docs](https://riscv-config.readthedocs.io/en/latest/new-extensions.html#adding-checks-through-checker-py-and-schemavalidator-py) -> [here](https://riscv-config.readthedocs.io/en/latest/code-doc.html#checker) 

If you can guide me how can we fix this , I would like to fix this :)

**Comment by neelgala** [comment]
since we use sphinx for the docs here.. all docs must be read on readthedocs. Reading RAW rst will always be an issue.
