### ISSUE TITLE
isa_validator inclusion tests are outdated

### ISSUE THREAD

**Issue by ssoler-smd** [riscv-software-src/riscv-config#83]
The tests for subextension inclusion are outdated and not consistent with the crypto and bitmanip extensions ratified last November. In the file there are references to "K", "Zkg" or "Zbp", which are not present under those names in the final ratified extensions.

**Comment by neelgala** [comment]
Unratified extensions or to be ratified extensions can remain in the isa string.  However, while Zbp is still unratified K and Zkg don't have any definitions and can be removed. Will raise a PR for this fix.
