### ISSUE TITLE
Detecting if PMPs are supported:  pmpaddr0/rv32/accessible == false,  all others must be false as well

### ISSUE THREAD

**Issue by billmcspadden-riscv** [riscv-software-src/riscv-config#88]
Context:  Sail configuration:   The Sail model has a command line switch, -P (pmp support enable), 
that needs to be replaced with a RISCV-Config setting.

Per @neelgala ,  this should be done by looking at /hart0/pmpaddr0/rv32/accessible.  I have extended
the check in the Sail model to:

 rv_enable_pmp         = 
        (
            (rv_cfg_bool_c("/hart0/pmpaddr0/rv32/accessible") ) ||
            (rv_cfg_bool_c("/hart0/pmpaddr0/rv64/accessible") )
        )
        ;

However,  the config validator should check for the condition that if pmpaddr0/accessible == false
then all other pmpaddrN/accessible are false as well.

**Comment by neelgala** [comment]
@billmcspadden-riscv thanks for filing this issue. I should get around to it soon. 

I think for pmp the following checks are required (can you confirm if I haven't missed anything):
1. check that all accessible pmp\[cfgs|addr\](n) csrs are contigous and start from n=0.
2. There should 0, 16 or 64 pmp\[cfgs|addr\](n) csrs accessible at any point. Some of which can be of type `ro_constant(0)`. 

So based on point-2 above, if n pmp csrs are accessible and m of those have their type as `ro_constant(0)` then the device has implemented only n-m pmp csrs.
